stages:
  - build
  - deploy
  - finish

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Build complete."

deploy-job:
  stage: deploy
  script:
    - docker compose build flask-app   # ensures multistage Dockerfile is used
    - docker compose up -d
  only:
    - main

finish-job:
  stage: finish
  script:
    - echo " Pipeline Completed..."
