stages:
  - build
  - deploy
  - finish

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Build complete."

deploy-job1:
  stage: deploy
  script:
    - docker compose up -d 

finish-job2:
  stage: finish
  script:
    - echo " Pipeline Completed..."